### ISSUE TITLE
Track navigation spinbox goes berserk at seemingly random times

### ISSUE THREAD

**Issue by mzipay** [mzipay/FLACManager#6]
Occasionally while editing metadata, the track navigation spinbox will start to "spin" by itself, rapidly.  Once this happens, there doesn't appear to be a way to make it stop except to exit the application. (Fortunately, File | Save metadata still functions in this case, so progress is not lost.)

Whenever this happens, the following traceback can be seen (over and over):

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/__init__.py", line 1550, in __call__
    return self.func(*args)
  File "./flacmanager.py", line 2219, in _refresh_track_editors
    track_vars = self.__track_vars[track_number]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by mzipay** [comment]
I've added tons of logging and tried a number of variations in how the Spinbox works with _refresh_track_editors, but nothing seems to eliminate this issue, and I haven't really found anything solid to explain why it happens.  I suspect this may be an issue with Tk on Mac OS X (XQuartz)...

In the meantime, a reasonable workaround is to simply put focus on the Spinbox and then use the up/down keyboard arrows.

**Comment by mzipay** [comment]
Observation: the traceback only appears if I attempt to explicitly click one of the Spinbox's arrows _while_ it is spinning uncontrollably.

The fact that the problem never occurs while using the focus+keyboard-up-or-down-arrow workaround just strengthens my opinion that the issue is in Tk (or possibly XQuartz or Tk+XQuartz).

I'm going to go back and compare against the pre-0.8.0 Spinbox code to see if I introduced this somehow in the refactoring.

**Comment by mzipay** [comment]
This is not a pressing issue for me.  The arrow keys workaround has actually become my preferred way to navigate the interface, and I am fairly certain this is a Quartz/tkinter bug. Since the next release will likely be the last for OS X anyway, I am closing this.
